### ISSUE TITLE
Cursor misposition

### ISSUE THREAD

**Issue by cbelleza** [ojkey/master#2]
When we want to enter a new number into a numberfield already filled in, the cursor moves to the first number position, what makes someone to move the cursor to the right position

**Comment by ReuDa** [comment]
I have the same problem.

Type "123", then mark the number (for example with CMD+A) and then type "4".

Result: Cursor in first position.

Everything works fine for me, if I just comment the "resetCursorPosition". I am not sure, what the original purpose of this method was...

**Comment by ojkey** [comment]
Could you checkout modifications and check it again, issue was fixed.

**Comment by ReuDa** [comment]
The issue is fixed, but I found a new one:

Type "12", use the arrow to set the cursor between "1" and "2" and use the delete key to delete the "2".

Result: Cursor in first position.

Why do you have to set the cursor? I just removed the resetCursorPosition-method-call an everything works fine in my case :-(

**Comment by ojkey** [comment]
It's interesting, I'll see it in the morning.

After formatting of entered string (adding grouping chars) I call setValue() and cursor moves to the end. So  I call resetCursorPosition to put cursor to the previous position.

**Comment by ReuDa** [comment]
Ah! Ok, cursor-positioning is used for the grouping-feature. I don't use this feature, that's why i didn't have any problems without resetCursorPosition().

**Comment by ojkey** [comment]
I've made some changes, is this bug still there?

**Comment by mandarinka2017** [comment]
The bug is gone. Could you please publish the atrifact to vaadin-addons repo?

**Comment by ReuDa** [comment]
The artifact "widgets-root" cannot be found, when installed via maven from vaadin-addons repo.
