### ISSUE TITLE
Zero might be a valid non-decimal option.

### ISSUE THREAD

**Issue by ReuDa** [ojkey/master#3]
In my case users are allowed to enter a zero.

For example: "Number of children" - there are people without children out there ;-)

I just deleted the lines and everything works fine. (Also the replacement of leading zeros if you enter "01" for example)

```
        if (charCode == '0' && curPos == 0 && !decimal) {
         event.preventDefault();
        }
```

**Comment by ojkey** [comment]
I used this check to prevent entering of numbers which couldn't start with zero, for instance integers.
May be it's required to add flag to disable this check in some cases?

**Comment by ReuDa** [comment]
I wouldn't say that you need a flag for that. Entering a single zero should be valid. That's independent from you feature of deleting leading zeros. If i delete the code mentioned in my first post and type "07" into the box, the value is replaced by "7" - which is perfect.

**Comment by ojkey** [comment]
Alles klar. I understood you, I'll fix it.
